apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yaml: |
{{ .Files.Get "prometheus.yaml" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-config
  namespace: {{ .Values.namespace }}
data:
  rules.yaml: |
{{ .Files.Get "rules.yaml" | indent 4}}

